name: full_text_search_plus
version: 1.0.0
homepage: https://github.com/martin-headspace/full_text_search
description: Full-text search that takes advantages of isolates to prevent locking the main thread

environment:
  sdk: '>=2.19.0 <3.4.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
